vich_uploader:
    db_driver: orm

    mappings:
        image:
            uri_prefix: /images/participants
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug'}
