vich_uploader:
    db_driver: orm

    mappings:
        image_participant:
            uri_prefix: /uploads/participants
            upload_destination: '%kernel.project_dir%/public/uploads/participants'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
